wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692260906.278525
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.8.16
      5: 0.14.2
      8:
      - 3
      - 5
